package com.ws101.gallamora.torres.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a product category (e.g., Electronics, Accessories).
 * <p>
 * This is the <strong>parent</strong> side of the One-to-Many relationship with
 * {@link Product}. One Category can have many Products. The actual foreign key
 * column lives on the {@link Product} table (the child/owning side).
 * </p>
 *
 * @author P.M A. Gallamora
 * @author P.G C. Torres
 */
@Entity
@Table(name = "categories")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Category {

    /** Primary key – auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The display name of the category (e.g., "Electronics").
     * Cannot be blank and must be unique across the table.
     */
    @Column(nullable = false, unique = true)
    private String name;

    /**
     * The list of products that belong to this category.
     * <p>
     * {@code mappedBy = "category"} tells JPA that the {@link Product#category}
     * field owns the relationship and holds the foreign key column.
     * {@code CascadeType.ALL} propagates save/delete operations from a Category
     * down to its Products automatically.
     * {@code FetchType.LAZY} defers loading products until they are actually
     * accessed, which improves performance.
     * {@code orphanRemoval = true} deletes a Product automatically when it is
     * removed from this list.
     * </p>
     */
    @OneToMany(
            mappedBy = "category",
            cascade = CascadeType.ALL,
            fetch = FetchType.LAZY,
            orphanRemoval = true)
    private List<Product> products = new ArrayList<>();
}
