package com.ws101.gallamora.torres.EcommerceApi.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a customer order.
 * <p>
 * This is the <strong>parent (inverse)</strong> side of the One-to-Many relationship
 * with {@link OrderItem}. One Order contains many OrderItems. The foreign key
 * {@code order_id} lives on the {@link OrderItem} table (the child/owning side).
 * </p>
 *
 * @author P.M A. Gallamora
 * @author P.G C. Torres
 */
@Entity
@Table(name = "orders")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Order {

    /** Primary key – auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the customer who placed the order. */
    @Column(nullable = false)
    private String customerName;

    /** Timestamp recording when the order was created. */
    @Column(nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * The line items belonging to this order.
     * <p>
     * {@code mappedBy = "order"} tells JPA that {@link OrderItem#order} owns the
     * relationship and holds the foreign key column.
     * {@code CascadeType.ALL} ensures that saving or deleting an Order automatically
     * propagates the same operation to its OrderItems.
     * {@code FetchType.LAZY} avoids eagerly loading every OrderItem every time an
     * Order is fetched, which is important for performance.
     * {@code orphanRemoval = true} deletes an OrderItem from the database when it
     * is removed from this list.
     * </p>
     */
    @OneToMany(
            mappedBy = "order",
            cascade = CascadeType.ALL,
            fetch = FetchType.LAZY,
            orphanRemoval = true)
    private List<OrderItem> items = new ArrayList<>();

    /**
     * Convenience helper to compute the total price of this order
     * by summing each line item's subtotal.
     *
     * @return the sum of (unit price × quantity) for every OrderItem
     */
    public double getTotalPrice() {
        return items.stream()
                .mapToDouble(item -> item.getUnitPrice() * item.getQuantity())
                .sum();
    }
}
