package com.ws101.gallamora.torres.EcommerceApi.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a single line item inside an {@link Order}.
 * <p>
 * This is the <strong>owning (child)</strong> side of the One-to-Many relationship
 * with {@link Order}. The {@code order_id} foreign key column lives on this table.
 * Each OrderItem records which product was purchased, at what price, and in what
 * quantity.
 * </p>
 *
 * @author P.M A. Gallamora
 * @author P.G C. Torres
 */
@Entity
@Table(name = "order_items")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class OrderItem {

    /** Primary key – auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The order this line item belongs to.
     * <p>
     * This is the <strong>owning side</strong> of the One-to-Many relationship.
     * {@code @JoinColumn(name = "order_id")} creates the {@code order_id} foreign
     * key column on the {@code order_items} table.
     * {@code FetchType.LAZY} prevents the full Order from being loaded every time
     * an OrderItem is fetched, avoiding unnecessary queries.
     * {@link JsonIgnore} prevents infinite recursion during JSON serialisation
     * (OrderItem → Order → Items → OrderItem ...).
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "order_id", nullable = false)
    @JsonIgnore
    private Order order;

    /**
     * The product that was ordered.
     * Stored as a simple reference – we record the product's ID here so the
     * order history is preserved even if product details change later.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    /** Number of units ordered for this line item. Must be at least 1. */
    @Column(nullable = false)
    private int quantity;

    /**
     * The price per unit at the time of purchase.
     * Stored separately from {@link Product#price} so that price changes to a
     * product do not retroactively alter historical order data.
     */
    @Column(nullable = false)
    private double unitPrice;
}
