package com.ws101.gallamora.torres.EcommerceApi.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a product in the e-commerce store.
 * <p>
 * This entity maps to the {@code products} database table and is the
 * <strong>owning (child)</strong> side of the One-to-Many relationship with
 * {@link Category}. The {@code category_id} foreign key column lives here.
 * </p>
 *
 * @author P.M A. Gallamora
 * @author P.G C. Torres
 */
@Entity
@Table(name = "products")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Product {

    /** Unique identifier – auto-generated by the database (auto-increment). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Display name of the product.
     * Cannot be null; must be at least 2 characters (validated in the service layer).
     */
    @Column(nullable = false)
    private String name;

    /** Short description of what the product is. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Retail price of the product. Must be greater than zero. */
    @Column(nullable = false)
    private double price;

    /**
     * The category this product belongs to.
     * <p>
     * This is the <strong>owning side</strong> of the One-to-Many relationship with
     * {@link Category}. {@code @JoinColumn(name = "category_id")} creates the
     * {@code category_id} foreign key column on the {@code products} table.
     * {@code FetchType.LAZY} avoids loading the full Category object unless needed,
     * preventing unnecessary database queries (N+1 problem).
     * {@link JsonIgnore} prevents infinite recursion when serialising to JSON
     * (Product → Category → Products → Category ...).
     * </p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    @JsonIgnore
    private Category category;

    /**
     * Convenience field – the category name returned in API responses.
     * This is a transient (non-persisted) field populated in the service layer
     * so callers receive the category name without triggering a lazy-load.
     */
    @Transient
    private String categoryName;

    /** Number of units currently in stock. Must be zero or positive. */
    @Column(nullable = false)
    private int stockQuantity;

    /** URL pointing to the product image (optional). */
    private String imageUrl;
}
